// Generated by CoffeeScript 1.12.6
(function() {
  jQuery(function() {
    return $('.score-player').change(function() {
      var i, playerNumber, round, roundName, score, scoreRound;
      playerNumber = this.name.slice(-1);
      score = 0;
      for (round = i = 1; i <= 9; round = ++i) {
        roundName = 'score' + round + '-player' + playerNumber;
        scoreRound = Number($("input[name='" + roundName + "']").val());
        if (isNaN(scoreRound)) {
          scoreRound = 0;
        }
        score += scoreRound;
      }
      return $('#total-player' + playerNumber).text(score);
    });
  });

}).call(this);
